insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (1, 'Georges', 'McKew', 'Male', 'Senior Editor');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (2, 'Darlene', 'Labroue', 'Female', 'Engineer IV');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (3, 'Nil', 'Dome', 'Male', 'Budget/Accounting Analyst IV');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (4, 'Antonetta', 'Carine', 'Female', 'Associate Professor');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (5, 'Kaylee', 'Ingall', 'Female', 'Assistant Manager');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (6, 'Conrad', 'Jacop', 'Male', 'Design Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (7, 'Keen', 'Farnworth', 'Male', 'Systems Administrator III');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (8, 'Tory', 'Coppock.', 'Female', 'Senior Financial Analyst');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (9, 'Latrena', 'Tremayne', 'Female', 'Design Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (10, 'Erin', 'Dunstall', 'Female', 'VP Marketing');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (11, 'Elyssa', 'Tollit', 'Female', 'Assistant Manager');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (12, 'Klemens', 'Rimmer', 'Male', 'Professor');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (13, 'Spenser', 'Cotterrill', 'Male', 'Civil Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (14, 'Hilarius', 'Kinder', 'Male', 'Chief Design Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (15, 'Giffer', 'Frostick', 'Male', 'Administrative Assistant IV');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (16, 'Lynette', 'McCrudden', 'Female', 'Systems Administrator IV');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (17, 'Balduin', 'Ruggs', 'Male', 'Analog Circuit Design manager');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (18, 'Matthias', 'Heninghem', 'Male', 'Product Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (19, 'Shelba', 'Cayley', 'Female', 'VP Sales');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (20, 'Gusti', 'Sparwell', 'Female', 'Actuary');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (21, 'Stefania', 'Jorio', 'Female', 'Electrical Engineer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (22, 'Stanislaus', 'Curnick', 'Male', 'Project Manager');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (23, 'Hermie', 'Raun', 'Male', 'Marketing Manager');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (24, 'Daphene', 'Vina', 'Female', 'Business Systems Development Analyst');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (25, 'Paton', 'Diable', 'Male', 'Environmental Specialist');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (26, 'Abrahan', 'Drohun', 'Male', 'VP Accounting');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (27, 'Wilhelmine', 'Hilary', 'Female', 'Analyst Programmer');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (28, 'Roseann', 'Fancutt', 'Female', 'Human Resources Assistant IV');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (29, 'Leigh', 'Pinare', 'Male', 'Automation Specialist II');
insert into Trabajadores (id, nombre, apellido, genero, puestoTrabajo) values (30, 'Guillermo', 'Zorzutti', 'Male', 'Professor');
